import { Stack, useLocalSearchParams } from 'expo-router';
import { Share as ShareIcon } from 'lucide-react-native';
import { 
  View, 
  Text, 
  StyleSheet, 
  ScrollView, 
  TouchableOpacity,
  Alert as RNAlert,
  Platform,
  Share,
} from 'react-native';
import { useBusiness } from '@/contexts/BusinessContext';
import type { Document } from '@/types/business';

export default function DocumentDetailScreen() {
  const { id } = useLocalSearchParams();
  const { documents, business } = useBusiness();
  
  const document = documents.find(d => d.id === id) as Document | undefined;

  if (!document) {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>Document not found</Text>
      </View>
    );
  }

  const formatCurrency = (amount: number) => {
    const symbol = document.currency === 'USD' ? '$' : 'ZWL';
    return `${symbol}${amount.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-ZW', { 
      month: 'long', 
      day: 'numeric', 
      year: 'numeric' 
    });
  };

  const handleShare = async () => {
    const docTypeLabel = document.type.charAt(0).toUpperCase() + document.type.slice(1);
    
    let content = `${docTypeLabel.toUpperCase()}\n`;
    content += `${'='.repeat(50)}\n\n`;
    content += `${docTypeLabel} Number: ${document.documentNumber}\n`;
    content += `Date: ${formatDate(document.date)}\n\n`;
    
    content += `FROM:\n`;
    content += `${business?.name}\n`;
    if (business?.phone) content += `${business.phone}\n`;
    if (business?.location) content += `${business.location}\n`;
    content += `\n`;
    
    content += `TO:\n`;
    content += `${document.customerName}\n`;
    if (document.customerPhone) content += `${document.customerPhone}\n`;
    content += `\n`;
    
    content += `ITEMS:\n`;
    content += `${'-'.repeat(50)}\n`;
    document.items.forEach((item, index) => {
      content += `${index + 1}. ${item.description}\n`;
      content += `   Qty: ${item.quantity} x ${formatCurrency(item.unitPrice)} = ${formatCurrency(item.total)}\n`;
    });
    content += `${'-'.repeat(50)}\n\n`;
    
    content += `SUBTOTAL: ${formatCurrency(document.subtotal)}\n`;
    if (document.tax) {
      content += `TAX: ${formatCurrency(document.tax)}\n`;
    }
    content += `TOTAL: ${formatCurrency(document.total)}\n\n`;
    
    if (document.notes) {
      content += `NOTES:\n${document.notes}\n\n`;
    }
    
    content += `\nGenerated by DreamBig Business OS`;

    try {
      if (Platform.OS === 'web') {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = window.document.createElement('a');
        a.href = url;
        a.download = `${document.documentNumber}-${document.customerName}.txt`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        await Share.share({
          message: content,
          title: `${docTypeLabel} ${document.documentNumber}`,
        });
      }
    } catch (error) {
      console.error('Share failed:', error);
      RNAlert.alert('Error', 'Failed to share document');
    }
  };

  const docTypeLabel = document.type.charAt(0).toUpperCase() + document.type.slice(1);

  return (
    <>
      <Stack.Screen 
        options={{ 
          title: document.documentNumber,
          headerRight: () => (
            <TouchableOpacity onPress={handleShare} style={{ marginRight: 16 }}>
              <ShareIcon size={22} color="#0066CC" />
            </TouchableOpacity>
          )
        }} 
      />
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>{docTypeLabel}</Text>
          </View>
          <Text style={styles.docNumber}>{document.documentNumber}</Text>
          <Text style={styles.date}>{formatDate(document.date)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>From</Text>
          <View style={styles.infoCard}>
            <Text style={styles.businessName}>{business?.name}</Text>
            {business?.phone && <Text style={styles.infoText}>{business.phone}</Text>}
            {business?.location && <Text style={styles.infoText}>{business.location}</Text>}
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>To</Text>
          <View style={styles.infoCard}>
            <Text style={styles.customerName}>{document.customerName}</Text>
            {document.customerPhone && (
              <Text style={styles.infoText}>{document.customerPhone}</Text>
            )}
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Items</Text>
          {document.items.map((item, index) => (
            <View key={item.id} style={styles.itemCard}>
              <View style={styles.itemHeader}>
                <Text style={styles.itemNumber}>{index + 1}</Text>
                <View style={styles.itemInfo}>
                  <Text style={styles.itemDescription}>{item.description}</Text>
                  <Text style={styles.itemMeta}>
                    {item.quantity} x {formatCurrency(item.unitPrice)}
                  </Text>
                </View>
                <Text style={styles.itemTotal}>{formatCurrency(item.total)}</Text>
              </View>
            </View>
          ))}
        </View>

        <View style={styles.totalsCard}>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Subtotal</Text>
            <Text style={styles.totalValue}>{formatCurrency(document.subtotal)}</Text>
          </View>
          {document.tax && (
            <>
              <View style={styles.totalDivider} />
              <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>Tax</Text>
                <Text style={styles.totalValue}>{formatCurrency(document.tax)}</Text>
              </View>
            </>
          )}
          <View style={styles.totalDivider} />
          <View style={styles.totalRow}>
            <Text style={styles.totalLabelFinal}>Total</Text>
            <Text style={styles.totalValueFinal}>{formatCurrency(document.total)}</Text>
          </View>
        </View>

        {document.notes && (
          <View style={styles.notesCard}>
            <Text style={styles.notesTitle}>Notes</Text>
            <Text style={styles.notesText}>{document.notes}</Text>
          </View>
        )}

        <TouchableOpacity style={styles.shareButton} onPress={handleShare}>
          <ShareIcon size={20} color="#FFF" />
          <Text style={styles.shareButtonText}>Share Document</Text>
        </TouchableOpacity>
      </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  badge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#EFF6FF',
    marginBottom: 12,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#0066CC',
    textTransform: 'uppercase',
  },
  docNumber: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: '#0F172A',
    marginBottom: 4,
  },
  date: {
    fontSize: 15,
    color: '#64748B',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  infoCard: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  businessName: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#0F172A',
    marginBottom: 4,
  },
  customerName: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#0F172A',
    marginBottom: 4,
  },
  infoText: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 2,
  },
  itemCard: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 8,
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  itemNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    color: '#0066CC',
    fontSize: 12,
    fontWeight: '700' as const,
    textAlign: 'center',
    lineHeight: 24,
  },
  itemInfo: {
    flex: 1,
  },
  itemDescription: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#0F172A',
    marginBottom: 4,
  },
  itemMeta: {
    fontSize: 13,
    color: '#64748B',
  },
  itemTotal: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#0066CC',
  },
  totalsCard: {
    padding: 20,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    marginBottom: 16,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
  },
  totalLabel: {
    fontSize: 15,
    color: '#94A3B8',
  },
  totalValue: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#FFF',
  },
  totalDivider: {
    height: 1,
    backgroundColor: '#334155',
    marginVertical: 4,
  },
  totalLabelFinal: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#FFF',
  },
  totalValueFinal: {
    fontSize: 24,
    fontWeight: '700' as const,
    color: '#10B981',
  },
  notesCard: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FEF3C7',
    marginBottom: 16,
  },
  notesTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#92400E',
    marginBottom: 8,
  },
  notesText: {
    fontSize: 14,
    color: '#78350F',
    lineHeight: 20,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#0066CC',
  },
  shareButtonText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFF',
  },
  errorText: {
    fontSize: 16,
    color: '#EF4444',
    textAlign: 'center',
    marginTop: 40,
  },
});
