// This file is auto-generated by Expo Router
// It will be regenerated when you run `npx expo start`
// This is a placeholder to prevent TypeScript errors until Expo generates the actual file

declare module 'expo-router' {
  import { ComponentType } from 'react';
  
  interface StackComponent extends ComponentType<any> {
    Screen: ComponentType<any>;
  }
  
  interface TabsComponent extends ComponentType<any> {
    Screen: ComponentType<any>;
  }
  
  export const Stack: StackComponent;
  export const Tabs: TabsComponent;
  export const Slot: ComponentType<any>;
  export function useRouter(): any;
  export function useSegments(): string[];
  export function usePathname(): string;
  export function useLocalSearchParams(): Record<string, string | string[] | undefined>;
  export function useGlobalSearchParams(): Record<string, string | string[] | undefined>;
  export const router: any;
  export const Link: ComponentType<any>;
  export const Redirect: ComponentType<any>;
  export * from 'expo-router/types';
}
